services:
  study:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - haic-api
    restart: unless-stopped

  haic-api:
    build:
      context: ./services/haic_api
    env_file:
      .env.docker
    restart: unless-stopped
