FROM node:22-bookworm-slim AS build

WORKDIR /app

ARG VITE_BASE_PATH=/
ARG VITE_STORAGE_ENGINE=localStorage
ARG VITE_REPO_URL=https://github.com/revisit-studies/study
ARG VITE_FIREBASE_CONFIG=
ARG VITE_RECAPTCHAV3TOKEN=
ARG VITE_SUPABASE_URL=
ARG VITE_SUPABASE_ANON_KEY=

ENV VITE_BASE_PATH=$VITE_BASE_PATH
ENV VITE_STORAGE_ENGINE=$VITE_STORAGE_ENGINE
ENV VITE_REPO_URL=$VITE_REPO_URL
ENV VITE_FIREBASE_CONFIG=$VITE_FIREBASE_CONFIG
ENV VITE_RECAPTCHAV3TOKEN=$VITE_RECAPTCHAV3TOKEN
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY

COPY package.json yarn.lock ./
RUN corepack enable && yarn install --frozen-lockfile

COPY . .
RUN corepack yarn build

FROM nginx:1.27-alpine

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
